# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1,26.1.2]
neo_version=26.1.2.109
neo_version_range=[26.1,26.2)

# Mod Properties
mod_authors=unilock
mod_description=modpack fixes!
mod_group_id=cc.unilock.twentysix
mod_id=twentysix
mod_license=MIT
mod_name=TwentySix
mod_version=1.2.0
